package design

import (
	. "github.com/goadesign/goa/design"
	. "github.com/goadesign/goa/design/apidsl"
)


var _ = API("firstgoa", func() {		// "My API" is the name of the API used in docs
	Title("FirstGoa")			// Documentation title
	Description("API about goa example")	// Longer documentation description
	Host("193.168.1.32:8081")			// Host used by Swagger and clients
	Scheme("http") 				// HTTP scheme used by Swagger and clients
	BasePath("/firstgoa") 			// Base path to all API endpoints
	Consumes("application/json")		// Media types supported by the API
	Produces("application/json")		// Media types generated by the API
})

var _ = Resource("hello", func() {
	Action("say", func() {
		Routing(GET("/say/:words"))
		Description("say words and show in response")
		Params(func() {
			Param("words", String, "say words")
		})
		Response(OK, "plain/text")

	})

	Action("answer", func() {
		Routing(POST("/answer"))
		Description("answer words and show in response")
		Payload(Message)
		Response(OK)
	})
})

var Message = Type("message", func() {
	Description("message of user to send ")
	Attribute("user")
	Attribute("info", func() {
		Attribute("sendTime", DateTime, "user send message time")
		Attribute("content", String, "content of message")
	})
	Required("info")
})