// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "firstgoa": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/phxuecan/FirstGo/firstgoa/design
// --out=$(GOPATH)/src/github.com/phxuecan/FirstGo/firstgoa
// --version=v1.2.0-dirty

package app
